### ISSUE TITLE
sample: Multiline comments cause an inconsistent amount of items per line

### ISSUE THREAD

**Issue by jD91mZM2** [nix-community/nixpkgs-fmt#120]
Just played around in the WASM example a little.

## Input
```nix
[ one /*two*/ three four five six seven eight nine
]
```

## Output
```nix
[
  one /*two*/ three
  four
  five
  six
  seven
  eight
  nine
]

```

## Desired output

```nix
[
  one /*two*/
  three
  four
  five
  six
  seven
  eight
  nine
]
```

or maybe even the comment should be on its own line, not sure.

**Comment by matklad** [comment]
We allow trailing comments because sometimes folks put comment on the preceding line, and sometimes they put a comment right after an item. I'd say in `one /*two*/ three` it's hard to guess where exactly the comment was intended to go, so it's somewhat expected that we just don't touch it and require manual intervention. 

But, anyway, requireing a line break after a comment seems like a good thing to do.
