### ISSUE TITLE
sample: closing bracket line collapse

### ISSUE THREAD

**Issue by B4dM4n** [nix-community/nixpkgs-fmt#198]
Closing brackets in multi line strings don't get collapsed into the previous line.

## Input
```nix
let
  cfg = ''
    ${call
    (value: ''
        ${value}
      ''
    )
  }
  '';
in
cfg

```

## Output
```nix
let
  cfg = ''
    ${call
      (value: ''
        ${value}
      ''
        )
    }
  '';
in
cfg

```

## Desired output

```nix
let
  cfg = ''
    ${call
      (value: ''
        ${value}
      '')
    }
  '';
in
cfg

```

**Comment by B4dM4n** [comment]
I noticed, this has nothing to do with multi line strings.

The desired behavior currently only happens with `{ }` blocks. With other values the closing bracket will stay on the same line as it started.

## With `'' ''` block
### Input
```nix
let
  cfg = (''
      text
    ''
  );
in
cfg

```

### Output
```nix
let
  cfg = (''
    text
  ''
  );
in
cfg

```

## With `{ }` block
### Input
```nix
let
  cfg = ({
      inherit value;
    }
  );
in
cfg

```

### Output
```nix
let
  cfg = ({
    inherit value;
  });
in
cfg

```

**Comment by Rizary** [comment]
@B4dM4n The rule is whenever the user put `(` with `{` or `[`, then the formatter wil check whether exists newline between them. If before formatting, there isn't any newline for exampe `({`, then the closing bracket will also without newline, and vice versa.

The problem on node string happened because we're still figuring out how to make node string behave like the rest of node. 

Thank you for the issue.
