### ISSUE TITLE
sample: RuntimeError: unreachable executed

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nixpkgs-fmt#70]
## Input

```nix
{
  traceIf =
    # predicate to check
    pred:
```

## Output

```
RuntimeError: unreachable executed
```

**Comment by zimbatm** [comment]
@matklad do you know of any mutation or fuzz testing framework that we could use to uncover that type of bugs?

**Comment by matklad** [comment]
We use `libfuzzer-sys` in rust-analyzer:

https://github.com/rust-analyzer/rust-analyzer/tree/master/crates/ra_syntax/fuzz

https://github.com/rust-fuzz/libfuzzer-sys

Another approach is to use property-based testing + randomized text edits.


I believe this failure is due to the fact that rnix assumes that the syntax tree is complete, this is tracked in https://gitlab.com/jD91mZM2/rnix/issues/9. I just didn't get to actually fixed that :)

**Comment by zimbatm** [comment]
Looks like the issue is fixed :) I created https://github.com/nix-community/nixpkgs-fmt/issues/88 to track the fuzzing discussion
